export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_BY_CATEGORY = 'FETCH_PRODUCTS_BY_CATEGORY';
export const FETCH_PRODUCTS_BY_TAG = 'FETCH_PRODUCTS_BY_TAG';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_BRANDS = 'FETCH_BRANDS';
export const SORT_PRODUCTS_BY_PRICE = 'FILTER_PRODUCTS_BY_PRICE';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const RESET_REGISTER_STATE = 'RESET_REGISTER_STATE';

export const GET_CART = 'GET_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const EMPTY_CART = 'EMPTY_CART';
export const CART_ERROR = 'CART_ERROR'

export const GET_SHIPMENT_METHODS = 'GET_SHIPMENT_METHODS';
export const GET_PAYMENT_METHODS = 'GET_PAYMENT_METHODS';
export const SAVE_SHIPPING_INFOR = 'SAVE_SHIPPING_INFOR';
export const CHECKOUT_SUCCESS =  'CHECKOUT_SUCCESS';
export const CHECKOUT_ERROR = 'CHECKOUT_ERROR';

export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';
